config/routes.rb
SixDegreesOfKevinBacon::Application.routes.draw do
  
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  resources :movies do
    collection do
      get 'relations'
    end
  end
  
  resources :people
  
  root 'movies#index'
  
end

app/models/acting.rb
class Acting < ActiveRecord::Base
  
  validates_presence_of :person_id, :movie_id
  
  belongs_to :person
  belongs_to :movie, counter_cache: :actors_count
  
  validates_uniqueness_of :person_id, scope: :movie_id
  
  # include Neoid::Relationship
  # neoidable do |c|
  #   c.relationship start_node: :person, end_node: :movie, type: :acts_in
  #   c.relationship start_node: :person, end_node: :movie, type: :is_part_of
  # end
  
end

app/models/directing.rb
class Directing < ActiveRecord::Base
  
  validates_presence_of :person_id, :movie_id
  
  belongs_to :person
  belongs_to :movie, counter_cache: :directors_count
  
  validates_uniqueness_of :person_id, scope: :movie_id
  
  # include Neoid::Relationship
  # neoidable do |c|
  #   c.relationship start_node: :person, end_node: :movie, type: :directs
  #   c.relationship start_node: :person, end_node: :movie, type: :is_part_of
  # end
  
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  
  validates_presence_of :title, :imdb_id, :year
  validates_uniqueness_of :imdb_id
  
  has_many :actings, dependent: :destroy
  has_many :actors, through: :actings, source: :person
  
  has_many :directings, dependent: :destroy
  has_many :directors, through: :directings, source: :person
  
  # include Neoid::Node
  
end

app/models/person.rb
class Person < ActiveRecord::Base
  
  validates_presence_of :name, :imdb_id
  validates_uniqueness_of :imdb_id
  
  has_many :actings, dependent: :destroy
  has_many :acted_movies, through: :actings, source: :movie
  
  has_many :directings, dependent: :destroy
  has_many :directed_movies, through: :directings, source: :movie
  
  # include Neoid::Node
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  def index
    if params[:term] && params[:term].length > 2
      @movies = Movie.where('title ilike ?', "%#{params[:term]}%").limit(20).order('title')
    else
      @movies = Movie.limit(20).order('title').all
    end
    respond_to do |format|
      format.html
      format.json { render json: @movies }
    end
  end
  
  def relations
    @movie1 = Movie.find(params[:movie1_id])
    @movie2 = Movie.find(params[:movie2_id])
    
    max_degrees = 6
    found_connections = 0
    exclude_people = []
    @connections = []
    
    Timeout::timeout(20) do
    
      degree = 0
      while (degree < max_degrees && found_connections <= 0)
        new_connections = Movie.connection.query(build_pg_query(degree+1, exclude_people, {
          start_year: params[:start_year].to_i,
          end_year:   params[:end_year].to_i,
          max_nodes:  params[:max_nodes].to_i
        }))
      
        exclude_people += new_connections.map{|c| c[degree*2]}.uniq
        found_connections += new_connections.length
      
        @connections << new_connections
        degree += 1
      end
    
    end
    
    people_ids = []
    movie_ids  = []
    nodes = []
    @layers = []
    @edges = {}
    
    @connections.each_with_index do |conn, degree|
      conn.each do |row|
        hops = [@movie1.id.to_s, @movie1.year] + row
        
        i=0
        while i <= row.length-3
          from = hops[i]
          to   = hops[i+3]
          key  = Digest::MD5.hexdigest("#{from}#{to}")
          
          @edges[key] ||= {}
          @edges[key][:source] = from
          @edges[key][:target] = to
          @edges[key][:actors] ||= []
          @edges[key][:weight] ||= 0
          
          unless @edges[key][:actors].include? hops[i+1]
            @edges[key][:actors] << hops[i+1]
            @edges[key][:weight] += 1
          end
          
          @layers[i/3] ||= {}
          @layers[i/3][:nodes] ||= []
          @layers[i/3][:nodes] << to unless @layers[i/3][:nodes].include?(to)
          
          people_ids << hops[i+1]
          movie_ids  << from << to
          
          i += 3
        end
      end
    end
    
    people = Person.find(people_ids.uniq)
    movies = Movie.includes(:directors).find(movie_ids.uniq)
    @layers.each{|l| l[:nodes].map!{|id| movies.detect{|m| m.id.to_s==id}}}
    @layers = [{nodes: [@movie1]}] + @layers

    @edges = @edges.values
    @edges.each do |edge|
      edge[:actors].map!{|aid| people.detect{|p| p.id.to_s==aid}}
    end
    
    @response = {
      layers: @layers,
      links: @edges
    }
    
    respond_to do |format|
      format.html { redirect_to movies_path }
      format.json do
        render json: @response, callback: params[:callback]
      end
    end
  rescue Timeout::Error
    respond_to do |format|
      format.html { redirect_to movies_path }
      format.json do
        render json: {layers: [], links: []}, callback: params[:callback]
      end
    end
  end
  
  def build_pg_query(degrees, exclude_people=[], options={})
    options[:start_year] ||= 1900
    options[:end_year]   ||= 2017
    options[:max_nodes]  ||= 10
    
    if options[:start_year]<1900
      options[:start_year] = 1900
    elsif options[:start_year]>2017
      options[:start_year] = 2017
    end
    
    if options[:end_year]<1900
      options[:end_year] = 2017
    elsif options[:end_year]>2017
      options[:end_year] = 2017
    end
    
    if options[:max_nodes]<1
      options[:max_nodes] = 10
    elsif options[:max_nodes]>10
      options[:max_nodes] = 10
    end
    
    sql = "SELECT "
    sql << 1.upto(degrees).map{|i| "person_hop_#{i}.person_id, movie_hop_#{i}.movie_id, movie_hop_#{i}_movie.year"}.join(', ')
    sql << "\nFROM movies AS source \n"
    sql << "LEFT JOIN actings AS person_hop_1 ON person_hop_1.movie_id=source.id\n"
    sql << "LEFT JOIN actings AS movie_hop_1 ON movie_hop_1.person_id=person_hop_1.person_id\n"
    sql << "LEFT JOIN movies AS movie_hop_1_movie ON movie_hop_1.movie_id=movie_hop_1_movie.id\n"
    2.upto(degrees).each do |i|
      sql << "LEFT JOIN actings AS person_hop_#{i} ON person_hop_#{i}.movie_id=movie_hop_#{i-1}.movie_id\n"
      sql << "LEFT JOIN actings AS movie_hop_#{i}  ON movie_hop_#{i}.person_id=person_hop_#{i}.person_id\n"
      sql << "LEFT JOIN movies AS movie_hop_#{i}_movie ON movie_hop_#{i}.movie_id=movie_hop_#{i}_movie.id\n"
    end
    sql << "WHERE source.id=#{@movie1.id}\n"
    1.upto(degrees).each do |i|
      sql << "AND (movie_hop_#{i}_movie.year BETWEEN '#{options[:start_year]}' AND '#{options[:end_year]}')\n"
    end
    sql << "AND movie_hop_1.movie_id<>source.id\n"
    
    # exclude previous hops -------------------------------------------------
    2.upto(degrees).each do |i|
      (i-1).downto(1).each do |j|
        sql << " AND movie_hop_#{i}.movie_id<>movie_hop_#{j}.movie_id\n"
      end
    end
    # look for the target movie ---------------------------------------------
    sql << "AND (\n"
    sql << " " + 1.upto(degrees).map{|i| "movie_hop_#{i}.movie_id=#{@movie2.id}"}.join(' OR ')
    sql << "\n)\n"
    
    # prevent loops by excluding people ---------------------------------------
    if exclude_people.length > 0
      1.upto(degrees-1) do |i|
        sql << "AND person_hop_#{i}.person_id NOT IN (#{exclude_people.join(', ')})\n"
      end
    end
    
    sql << "ORDER BY " << 1.upto(degrees).map{|i| "movie_hop_#{i}.movie_id"}.join(', ')
    sql << "\nLIMIT #{options[:max_nodes]}"
    sql << ";\n"
    
    return sql
  end
  
  def show
    @movie = Movie.includes(:actors).find(params[:id])
  end
  
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  
  def index
    @people = Person.limit(30).all
  end
  
  def show
    @person = Person.includes(:acted_movies).find(params[:id])
    @actings = @person.actings.includes(:movie).order('movies.year DESC')
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
  <meta charset="utf-8">	
  <title>Some Degrees of IMDB</title>
  
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link data-turbolinks-track="true" href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" media="all" rel="stylesheet" />
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="wrapper">
    <h1><%= link_to 'Some Degrees of IMDB', movies_path %></h1>
    
    <%= yield %>
    
    <div id="footer">
      Stats: 
      <%= Movie.count %> movies /// 
      <%= Person.count %> people /// 
      <%= Acting.count %> actings /// 
      <%= Directing.count %> directings
    </div>
  </div>
  
  <div id="spinner_container" style="display:none">
    <span class="spinner_wrapper">
      <%= image_tag 'spinner.gif' %>
    </span>
  </div>
  
</body>
</html>

app/views/movies/index.html.erb
<div id="search">
  <%= form_tag relations_movies_path, method: 'get', id: 'search_form' %>
    <p style="float:left;margin-right:20px;"><label>Movie 1</label>
    <input type="text" name="movie1" id="movie1" style="width:400px" autocomplete="off" />
    <input type="hidden" value="" name="movie1_id" id="movie1_id" /></p>

    <p style="float:left"><label>Movie 2</label>
    <input type="text" name="movie2" id="movie2" style="width:400px" autocomplete="off" />
    <input type="hidden" value="" name="movie2_id" id="movie2_id" /></p>
    
    <div class="clear"></div>
    
    <table id="slider_table">
      <tr>
        <td>
          <label>Year from</label>
          <input type="text" class="sliderValue" data-index="0" value="1900" name="start_year" id="start_year" style="width:50px;" />
        </td>
        <td><div id="slider"></div></td>
        <td>
          <label>Year until</label>
          <input type="text" class="sliderValue" data-index="1" value="2017" name="end_year" id="end_year" style="width:50px;" />
        </td>
      </tr>
    </table>

    <p class="clear" style="margin-top:10px;"><input type="submit" value="Search" class="btn btn-success btn-large" /></p>
  </form>
</div>

<div id="graph">
  <div id="vis"></div>
</div>
<div id="left">
  <div id="charts" style="display:none">
    <h2>Number of films by release year</h2>
    
    <div id='year-chart'></div>
    <span class="x-axis-label">year</span>
    
    <div id='actor-chart'></div>   	
    <span class="x-axis-label">number of actors</span>
    
    <h2>Number of directors</h2>
    <div id='director-chart'></div>
    <span class="x-axis-label">number of films</span>
  </div>
  <div id="info"></div>
</div>
<div class="clear"></div>

<script type="text/javascript" charset="utf-8">
  var lastData;
  var myNetwork;
  
  $(function(){
    myNetwork = window.Network();
    
    
    $("#slider").slider({
        min: 1900,
        max: 2017,
        step: 1,
        values: [1900, 2017],
        slide: function(event, ui) {
            for (var i = 0; i < ui.values.length; ++i) {
                $("input.sliderValue[data-index=" + i + "]").val(ui.values[i]);
            }
        }
    });
    
    $('#search_form').on('submit', function(e){
      e.preventDefault();
      
      if ($('#movie1').val()=='' && $('#movie2').val()=='') {
        $('#search_form').effect('shake');
      }
      else {
        $('#spinner_container').show();
        
        $.ajax('<%= relations_movies_path(format: 'json') %>?'+$('#search_form').serialize(), {
          method: 'get',
          success: function(data){
            lastData = data;
            
            $('#spinner_container').hide();
            
            $('#vis').children().remove();
            
            myNetwork("#vis", data);
            
            $('#charts').show();
          },
          error: function(){
            $('#spinner_container').hide();
            alert('Sorry, but an error occured!');
          }
        })
      }
    })
  })
</script>

<script type="text/javascript" charset="utf-8">
  var defaultOptions = {
    minLength: 2,
    source: function( request, response ) {
      $.ajax({
        url: "<%= movies_url(format: 'json') %>"+"?term="+request.term,
        success: function( data ) {
          response( $.map( data, function( item ) {
            return {
              label: item.title + " ("+item.year+")",
              value: item.title + " ("+item.year+")",
              movieID: item.id
            }
          }));
        }
      });
    }
  }
  
  var movie1Options = {};
  var movie1Options = $.extend(movie1Options, defaultOptions, {
    select: function(event, ui) {
      $('#movie1').val(ui.item.value);
      $('#movie1_id').val(ui.item.movieID);
      return false;
    }
  });
  
  var movie2Options = {};
  var movie2Options = $.extend(movie2Options, defaultOptions, {
    select: function(event, ui) {
      $('#movie2').val(ui.item.value);
      $('#movie2_id').val(ui.item.movieID);
      return false;
    }
  })
  
  $('#movie1').autocomplete(movie1Options);
  
  $('#movie2').autocomplete(movie2Options);
</script>

app/views/movies/relations.html.erb
<h1>Relations</h1>

<p>
  <%= link_to @movie1.title, @movie1 %> &mdash;
  <%= link_to @movie2.title, @movie2 %>
</p>

app/views/movies/show.html.erb
<h1><%= @movie.title %> (<%= @movie.year %>)</h1>

<% if @movie.directors.length > 0 %>
<p><strong>Directed by: </strong> <%= raw @movie.directors.map{|d| link_to h(d.name), person_path(d) }.join(', ') %></p>

<hr />
<% end %>

<p><%= link_to 'IMDb', "http://anonym.to/?http://akas.imdb.com/title/#{@movie.imdb_id}" %></p>

<table border="1">
<% @movie.actings.each do |acting| %>
<tr>
  <td><%= link_to acting.person.name, acting.person %></td>
  <td><%= acting.role %></td>
</tr>
<% end %>
</table>

app/views/people/show.html.erb
<h1><%= @person.name %></h1>

<table border="1">
<% @actings.each do |acting| %>
<tr>
  <td><%= link_to "#{acting.movie.title} (#{acting.movie.year})", acting.movie %></td>
  <td><%= acting.role %></td>
</tr>
<% end %>
</table>